# general setting
batch_size: 16
input_size: 32
gt_size: 128
ch_size: 3
scale: 4
log_dir: '/content/drive/MyDrive/logs/Ultimate-SR/ESRGAN-MSE-noblur'
pretrain_name: null
cycle_mse: False
# generator setting
network_G:
    name: 'RRDB'
    nf: 64
    nb: 23
    apply_noise: False

# dataset setting
train_dataset:
    path: '/content/drive/MyDrive/data/div2k_hr/DIV2K_train_HR'
    num_samples: 32208
    using_bin: True
    using_flip: True
    using_rot: True
    detect_blur: True
    buffer_size: 1024           # max size of buffer
    patch_per_image: 128        # number of patches to extract from each image

test_dataset:
    set5: './test data/Set5'
    set14: './test data/Set14'

# training setting
niter: 500000
lr: !!float 2e-4
lr_steps: [200000, 400000]
lr_rate: 0.5

adam_beta1_G: 0.9
adam_beta2_G: 0.99

w_pixel: 1.0
pixel_criterion: l1

save_steps: 5000

# logging settings
logging:
    psnr: True
    lpips: True
    ssim: True
    plot_samples: True