# general setting
batch_size: 16
input_size: 32
gt_size: 512
ch_size: 3
scale: 16
log_dir: '/content/drive/MyDrive/logs/Ultimate-SR/ExtremeSR-MSE-RFB_ESRGAN'
pretrain_name: null
cycle_mse: False
# generator setting
network_G:
    name: 'RFB_ESRGAN'
    nf: 64
    nb_rrbd: 16
    nb_rfb: 8
    apply_noise: False

# dataset setting
train_dataset:
    path: '/content/drive/MyDrive/data/DIV8K'
    num_samples: 32208
    using_bin: True
    using_flip: True
    using_rot: True
    detect_blur: False
    buffer_size: 1024           # min size of buffer
    patch_per_image: 128        # number of patches to extract from each image

test_dataset:
    set5: './test data/Set5'
    set14: './test data/Set14'
    DIV8K: '/content/drive/MyDrive/data/DIV8K_val_cropped'
    DIV8K_crop_centor: 0     # crop center 1008 pixels (1008 % 16==0)

# training setting
niter: 100000
lr: !!float 2e-4
lr_steps: [25000, 50000, 75000]
lr_rate: 0.5

adam_beta1_G: 0.9
adam_beta2_G: 0.99

w_pixel: 1.0
pixel_criterion: l1

save_steps: 5000

# logging settings
logging:
    psnr: True
    lpips: True
    ssim: True
    plot_samples: True