# general setting
batch_size: 3
input_size: 32
gt_size: 512
ch_size: 3
scale: 16
log_dir: '/content/drive/MyDrive/logs/Ultimate-SR/ExtremeSR-cycle-RFB_ESRGAN'
pretrain_dir: '/content/drive/MyDrive/logs/Ultimate-SR/ExtremeSR-MSE-RFB_ESRGAN-blurdetect'  # directory to load from at initial training
cycle_mse: True

# generator setting
network_G:
    name: 'RFB_ESRGAN'
    nf: 64
    nb_rrbd: 16
    nb_rfb: 8
    apply_noise: True
# discriminator setting
network_D:
    nf: 64

# dataset setting
train_dataset:
    path: '/content/drive/MyDrive/data/DIV8K'
    num_samples: 32208
    using_bin: True
    using_flip: True
    using_rot: True
    detect_blur: True
    buffer_size: 1024           # max size of buffer
    patch_per_image: 128        # number of patches to extract from each image
test_dataset:
    set5: './test data/Set5'
    set14: './test data/Set14'
    DIV8K: '/content/drive/MyDrive/data/DIV8K_val_cropped'
    DIV8K_crop_centor: 0     # crop center 1008 pixels (1008 % 16==0)

# training setting
niter: 400000

lr_G: !!float 2e-5
lr_D: !!float 2e-5
lr_steps: [50000, 100000, 200000, 300000]
lr_rate: 0.5

adam_beta1_G: 0.9
adam_beta2_G: 0.99
adam_beta1_D: 0.9
adam_beta2_D: 0.99

w_pixel: 10
pixel_criterion: l1

w_feature: 1.0
feature_criterion: l1

w_gan: !!float 5e-3
gan_type: ragan  # gan | ragan
refgan: True       # provide reference image

save_steps: 5000

# logging settings
logging:
    psnr: True
    lpips: True
    ssim: True
    plot_samples: True